# Generated by Django 4.0.6 on 2022-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('info_timestamp', models.DateTimeField()),
                ('info_modified_timestamp', models.DateTimeField()),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('en_title', models.CharField(max_length=255)),
                ('ja_title', models.CharField(max_length=255)),
                ('medium_picture', models.CharField(max_length=255)),
                ('large_picture', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('synopsis', models.TextField()),
                ('mean', models.FloatField()),
                ('rank', models.PositiveSmallIntegerField()),
                ('popularity', models.PositiveSmallIntegerField()),
                ('num_list_users', models.PositiveSmallIntegerField()),
                ('num_scoring_users', models.PositiveSmallIntegerField()),
                ('nsfw', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('media_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('num_episodes', models.PositiveSmallIntegerField()),
                ('start_season_year', models.PositiveSmallIntegerField()),
                ('start_season_season', models.CharField(max_length=255)),
                ('braodcast_day_of_the_week', models.CharField(max_length=255)),
                ('broadcast_start_time', models.TimeField()),
                ('source', models.CharField(max_length=255)),
                ('average_episode_duration', models.PositiveSmallIntegerField()),
                ('rating', models.CharField(max_length=255)),
                ('background', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
