# Generated by Django 4.0.6 on 2022-07-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='en_title',
            new_name='alternative_titles_en_title',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='ja_title',
            new_name='alternative_titles_ja_title',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='large_picture',
            new_name='main_picture_large',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='medium_picture',
            new_name='main_picture_medium',
        ),
        migrations.CreateModel(
            name='AnimeRelatedAnime',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='main.anime')),
                ('related_anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_anime', to='main.anime')),
            ],
        ),
    ]
