# Generated by Django 4.0.6 on 2022-07-14 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_en_title_anime_alternative_titles_en_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeRecommendation',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('recommendations', models.PositiveSmallIntegerField()),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRecommendation_anime', to='main.anime')),
                ('related_anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRecommendation_related_anime', to='main.anime')),
            ],
        ),
    ]
