# Generated by Django 4.0.6 on 2022-07-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mangarelatedanime_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animealternativetitles',
            table='anime_alternative_titles',
        ),
        migrations.AlterModelTable(
            name='animerecommendation',
            table='anime_recommendation',
        ),
        migrations.AlterModelTable(
            name='mangarecommendation',
            table='manga_recommendation',
        ),
        migrations.AlterModelTable(
            name='mangarelatedanime',
            table='manga_related_anime',
        ),
    ]
