# Generated by Django 4.0.6 on 2022-07-14 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_animerecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animerelatedanime',
            name='anime_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedAnime_anime', to='main.anime'),
        ),
        migrations.AlterField(
            model_name='animerelatedanime',
            name='related_anime_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedAnime_related_anime', to='main.anime'),
        ),
        migrations.CreateModel(
            name='AnimeGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genres')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeAlternativeTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
            ],
        ),
    ]
