# Generated by Django 4.0.6 on 2022-07-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_animerelatedanime_anime_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('info_timestamp', models.DateTimeField()),
                ('info_modified_timestamp', models.DateTimeField()),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('main_picture_medium', models.CharField(max_length=255)),
                ('main_picture_large', models.CharField(max_length=255)),
                ('alternative_titles_en_title', models.CharField(max_length=255)),
                ('alternative_titles_ja_title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('synopsis', models.TextField()),
                ('mean', models.FloatField()),
                ('rank', models.PositiveSmallIntegerField()),
                ('popularity', models.PositiveSmallIntegerField()),
                ('num_list_users', models.PositiveSmallIntegerField()),
                ('num_scoring_users', models.PositiveSmallIntegerField()),
                ('nsfw', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('media_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('num_volumes', models.PositiveSmallIntegerField()),
                ('num_chapters', models.PositiveSmallIntegerField()),
                ('background', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='alternative_titles_en_title',
            new_name='alternative_titles_en',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='alternative_titles_ja_title',
            new_name='alternative_titles_ja',
        ),
    ]
