# Generated by Django 4.0.6 on 2022-07-27 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_importque_importque_type_media_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animerelatedanime',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedAnime_Anime_media', to='main.anime'),
        ),
        migrations.AlterField(
            model_name='animerelatedanime',
            name='related_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedAnime_Anime_related_media', to='main.anime'),
        ),
        migrations.AlterField(
            model_name='animerelatedmanga',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedManga_Anime_media', to='main.anime'),
        ),
        migrations.AlterField(
            model_name='animerelatedmanga',
            name='related_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedManga_Manga_related_media', to='main.manga'),
        ),
    ]
