# Generated by Django 4.0.6 on 2022-07-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_manga_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='braodcast_day_of_the_week',
            new_name='broadcast_day_of_the_week',
        ),
    ]
