# Generated by Django 4.0.6 on 2022-07-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_animerelatedanime_media_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimeRecommendation',
            new_name='AnimeRecs',
        ),
        migrations.RenameModel(
            old_name='MangaRecommendation',
            new_name='MangaRecs',
        ),
        migrations.RemoveConstraint(
            model_name='animerecs',
            name='AnimeRecommendation_media_recommended_media',
        ),
        migrations.RemoveConstraint(
            model_name='mangarecs',
            name='MangaRecommendation_media_recommended_media',
        ),
        migrations.AlterField(
            model_name='mangarelatedanime',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MangaRelatedAnime_Manga_media', to='main.manga'),
        ),
        migrations.AlterField(
            model_name='mangarelatedanime',
            name='related_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MangaRelatedAnime_Anime_related_media', to='main.anime'),
        ),
        migrations.AddConstraint(
            model_name='animerecs',
            constraint=models.UniqueConstraint(fields=('media', 'recommended_media'), name='AnimeRecs_media_recommended_media'),
        ),
        migrations.AddConstraint(
            model_name='mangarecs',
            constraint=models.UniqueConstraint(fields=('media', 'recommended_media'), name='MangaRecs_media_recommended_media'),
        ),
        migrations.AlterModelTable(
            name='animerecs',
            table='anime_recs',
        ),
        migrations.AlterModelTable(
            name='mangarecs',
            table='manga_recs',
        ),
    ]
