# Generated by Django 4.0.6 on 2022-07-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_braodcast_day_of_the_week_anime_broadcast_day_of_the_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animerelatedanime',
            name='anime_id',
        ),
        migrations.RemoveField(
            model_name='animerelatedanime',
            name='related_anime_id',
        ),
        migrations.AddField(
            model_name='animerelatedanime',
            name='main_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedAnime_main_id', to='main.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animerelatedanime',
            name='related_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedAnime_related_id', to='main.anime'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AnimeRelatedManga',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedManga_main_id', to='main.anime')),
                ('related_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedManga_related_id', to='main.manga')),
            ],
        ),
    ]
