# Generated by Django 4.0.6 on 2022-07-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_animerelatedanime_anime_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animerelatedanime',
            name='main_id',
        ),
        migrations.RemoveField(
            model_name='animerelatedmanga',
            name='main_id',
        ),
        migrations.AddField(
            model_name='animerelatedanime',
            name='media_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedAnime_media_id', to='main.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animerelatedmanga',
            name='media_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedManga_media_id', to='main.anime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='broadcast_start_time',
            field=models.TimeField(null=True),
        ),
    ]
