# Generated by Django 4.0.6 on 2022-07-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_animerelatedanime_main_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animerecommendation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='animerelatedanime',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='animerelatedmanga',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
