# Generated by Django 4.0.6 on 2022-08-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_anime_start_date_alter_manga_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animegenres',
            old_name='anime',
            new_name='media',
        ),
        migrations.AddField(
            model_name='user',
            name='alternative_titles_en',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='alternative_titles_ja',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MangaGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genres')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manga')),
            ],
            options={
                'db_table': 'manga_genres',
            },
        ),
    ]
