# Generated by Django 4.0.6 on 2022-08-01 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_mangaalternativetitles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animealternativetitles',
            old_name='anime',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='mangaalternativetitles',
            old_name='anime',
            new_name='media',
        ),
        migrations.CreateModel(
            name='MangaPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=255)),
                ('large', models.CharField(max_length=255)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manga')),
            ],
            options={
                'db_table': 'manga_pictures',
            },
        ),
        migrations.CreateModel(
            name='AnimePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=255)),
                ('large', models.CharField(max_length=255)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
            ],
            options={
                'db_table': 'anime_pictures',
            },
        ),
    ]
