# Generated by Django 4.0.6 on 2022-07-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_manga_sparse'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='sparse',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
