# Generated by Django 4.0.6 on 2022-08-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_anime_animealternativetitles_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alternative_titles_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alternative_titles_ja',
        ),
        migrations.AddField(
            model_name='anime',
            name='alternative_titles_en',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='alternative_titles_ja',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manga',
            name='alternative_titles_en',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manga',
            name='alternative_titles_ja',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
