# Generated by Django 4.0.6 on 2022-07-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_anime_sparse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animerecommendation',
            name='anime_id',
        ),
        migrations.RemoveField(
            model_name='animerecommendation',
            name='related_anime_id',
        ),
        migrations.RemoveField(
            model_name='animerelatedanime',
            name='media_id',
        ),
        migrations.RemoveField(
            model_name='animerelatedanime',
            name='related_id',
        ),
        migrations.RemoveField(
            model_name='animerelatedmanga',
            name='media_id',
        ),
        migrations.RemoveField(
            model_name='animerelatedmanga',
            name='related_id',
        ),
        migrations.AddField(
            model_name='animerecommendation',
            name='media',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRecommendation_media', to='main.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animerecommendation',
            name='recommended',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRecommendation_recommended', to='main.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animerelatedanime',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedAnime_media', to='main.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animerelatedanime',
            name='related',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedAnime_related', to='main.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animerelatedmanga',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedManga_media', to='main.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animerelatedmanga',
            name='related',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedManga_related', to='main.manga'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MangaRelatedManga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MangaRelatedManga_media', to='main.manga')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MangaRelatedManga_related', to='main.manga')),
            ],
        ),
        migrations.CreateModel(
            name='MangaRelatedAnime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MangaRelatedAnime_media', to='main.manga')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MangaRelatedAnime_related', to='main.anime')),
            ],
        ),
        migrations.CreateModel(
            name='MangaRecommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendations', models.PositiveSmallIntegerField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MangaRecommendation_media', to='main.manga')),
                ('recommended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MangaRecommendation_recommended', to='main.anime')),
            ],
        ),
    ]
