# Generated by Django 4.0.6 on 2022-07-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_animerecommendation_anime_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animerecommendation',
            name='recommended',
        ),
        migrations.RemoveField(
            model_name='mangarecommendation',
            name='recommended',
        ),
        migrations.AddField(
            model_name='animerecommendation',
            name='recommended_media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRecommendation_recommended_media', to='main.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangarecommendation',
            name='recommended_media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='MangaRecommendation_recommended_media', to='main.anime'),
            preserve_default=False,
        ),
    ]
