# Generated by Django 4.0.6 on 2022-08-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_user_alternative_titles_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaSynonyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=255)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manga')),
            ],
            options={
                'db_table': 'manga_synonyms',
            },
        ),
        migrations.CreateModel(
            name='AnimeSynonyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=255)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
            ],
            options={
                'db_table': 'anime_synonyms',
            },
        ),
    ]
