# Generated by Django 4.0.6 on 2022-08-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_mangasynonyms_animesynonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='statistics_num_list_users',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='statistics_status_completed',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='statistics_status_dropped',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='statistics_status_on_hold',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='statistics_status_plan_to_watch',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='statistics_status_watching',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='statistics_num_list_users',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='statistics_status_completed',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='statistics_status_dropped',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='statistics_status_on_hold',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='statistics_status_plan_to_watch',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='statistics_status_watching',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
