# Generated by Django 4.0.6 on 2022-07-14 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_animerecommendation_recommended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animerelatedanime',
            name='related',
        ),
        migrations.RemoveField(
            model_name='animerelatedmanga',
            name='related',
        ),
        migrations.RemoveField(
            model_name='mangarelatedanime',
            name='related',
        ),
        migrations.RemoveField(
            model_name='mangarelatedmanga',
            name='related',
        ),
        migrations.AddField(
            model_name='animerelatedanime',
            name='related_media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedAnime_related_media', to='main.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animerelatedmanga',
            name='related_media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AnimeRelatedManga_related_media', to='main.manga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangarelatedanime',
            name='related_media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='MangaRelatedAnime_related_media', to='main.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangarelatedmanga',
            name='related_media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='MangaRelatedManga_related_media', to='main.manga'),
            preserve_default=False,
        ),
    ]
