# Generated by Django 4.0.6 on 2022-08-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_anime_statistics_num_list_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'studio',
            },
        ),
        migrations.CreateModel(
            name='MangaStudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manga')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studio')),
            ],
            options={
                'db_table': 'manga_studios',
            },
        ),
        migrations.CreateModel(
            name='AnimeStudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studio')),
            ],
            options={
                'db_table': 'anime_studios',
            },
        ),
    ]
