# Generated by Django 4.0.6 on 2022-08-01 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_studio_mangastudios_animestudios'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaGenreList',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'manga_genre_list',
            },
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='AnimeGenreList',
        ),
        migrations.AlterModelTable(
            name='animegenrelist',
            table='anime_genre_list',
        ),
        migrations.AlterField(
            model_name='mangagenres',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mangagenrelist'),
        ),
    ]
