# Generated by Django 4.0.6 on 2022-07-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_user_usermanga_useranime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanga',
            old_name='is_rewatching',
            new_name='is_rereading',
        ),
        migrations.RenameField(
            model_name='usermanga',
            old_name='num_episodes_watched',
            new_name='num_chapters_read',
        ),
        migrations.AddField(
            model_name='usermanga',
            name='num_volumes_read',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
