# Generated by Django 4.0.6 on 2022-08-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_mangagenrelist_rename_genres_animegenrelist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importque',
            name='priority',
        ),
    ]
