# Generated by Django 4.0.6 on 2022-07-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_is_rewatching_usermanga_is_rereading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='mean',
            field=models.FloatField(null=True),
        ),
    ]
