# Generated by Django 4.0.6 on 2022-08-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_importque_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='importque',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
