# Generated by Django 4.0.6 on 2022-08-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_anime_average_episode_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='start_season_season',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
