# Generated by Django 4.0.6 on 2022-07-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_anime_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
