# Generated by Django 4.0.6 on 2022-08-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_anime_start_season_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
