# Generated by Django 4.0.6 on 2022-07-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_anime_start_season_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanga',
            name='finish_date',
            field=models.DateField(null=True),
        ),
    ]
