# Generated by Django 4.0.6 on 2022-07-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_useranime_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='popularity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
