# Generated by Django 4.0.6 on 2022-07-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_anime_num_scoring_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportQue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('media_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='anime',
            name='num_list_users',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='num_scoring_users',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='popularity',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='importque',
            constraint=models.UniqueConstraint(fields=('type', 'media_id'), name='ImportQue_type_media_id'),
        ),
    ]
