# Generated by Django 4.0.6 on 2022-07-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_user_anime_count_user_manga_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_anime_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='average_manga_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
