# Generated by Django 4.0.6 on 2022-07-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_user_average_anime_score_user_average_manga_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranime',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
