# Generated by Django 4.0.6 on 2022-07-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_useranime_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranime',
            name='num_episodes_watched',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
