# Generated by Django 4.0.6 on 2022-07-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_useranime_num_episodes_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_profile',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
