# Generated by Django 4.0.6 on 2022-07-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_user_private_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='private_profile',
            new_name='error',
        ),
    ]
