# Generated by Django 4.0.6 on 2022-07-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rename_private_profile_user_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='error',
            new_name='private',
        ),
    ]
