# Generated by Django 4.0.6 on 2022-07-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_error_user_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_successful_import',
            field=models.DateTimeField(default='1999-01-01'),
            preserve_default=False,
        ),
    ]
