# Generated by Django 4.0.6 on 2022-07-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_user_last_successful_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_successful_import',
            field=models.DateTimeField(null=True),
        ),
    ]
