# Generated by Django 4.0.6 on 2022-07-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_user_last_successful_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anime_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='average_anime_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='average_manga_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='manga_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
