# Generated by Django 4.0.6 on 2022-07-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_user_anime_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangarecommendation',
            name='recommended_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MangaRecommendation_recommended_media', to='main.manga'),
        ),
    ]
