# Generated by Django 4.0.6 on 2022-07-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_mangarecommendation_recommended_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
