# Generated by Django 4.0.6 on 2022-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_manga_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='mean',
            field=models.FloatField(null=True),
        ),
    ]
