# Generated by Django 4.0.6 on 2022-07-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_manga_mean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='private',
            new_name='anime_list_private',
        ),
        migrations.AddField(
            model_name='user',
            name='manga_list_private',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
