# Generated by Django 4.0.6 on 2022-07-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_rename_private_user_anime_list_private_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_successful_import',
            new_name='last_successful_anime_list_import',
        ),
        migrations.AddField(
            model_name='user',
            name='last_successful_manga_list_import',
            field=models.DateTimeField(null=True),
        ),
    ]
