# Generated by Django 4.0.6 on 2022-07-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_rename_last_successful_import_user_last_successful_anime_list_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animerelatedanime',
            name='relationship',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animerelatedmanga',
            name='relationship',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangarelatedanime',
            name='relationship',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangarelatedmanga',
            name='relationship',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
