# Generated by Django 4.0.6 on 2022-07-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_animerelatedanime_relationship_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='animerelatedanime',
            name='AnimeRelatedAnime_media_related_media',
        ),
        migrations.RemoveConstraint(
            model_name='animerelatedmanga',
            name='AnimeRelatedManga_media_related_media',
        ),
        migrations.RemoveConstraint(
            model_name='mangarelatedanime',
            name='MangaRelatedAnime_media_related_media',
        ),
        migrations.RemoveConstraint(
            model_name='mangarelatedmanga',
            name='MangaRelatedManga_media_related_media',
        ),
        migrations.AddConstraint(
            model_name='animerelatedanime',
            constraint=models.UniqueConstraint(fields=('media', 'related_media', 'relationship'), name='AnimeRelatedAnime_media_related_media_relationship'),
        ),
        migrations.AddConstraint(
            model_name='animerelatedmanga',
            constraint=models.UniqueConstraint(fields=('media', 'related_media', 'relationship'), name='AnimeRelatedManga_media_related_media_relationship'),
        ),
        migrations.AddConstraint(
            model_name='mangarelatedanime',
            constraint=models.UniqueConstraint(fields=('media', 'related_media', 'relationship'), name='MangaRelatedAnime_media_related_media_relationship'),
        ),
        migrations.AddConstraint(
            model_name='mangarelatedmanga',
            constraint=models.UniqueConstraint(fields=('media', 'related_media', 'relationship'), name='MangaRelatedManga_media_related_media_relationship'),
        ),
    ]
